name: CI build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Upload artifact
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: binary-${{ matrix.os }}
        path: apnstool
      
    - name: Upload artifact
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: binary-${{ matrix.os }}
        path: apnstool.exe
