name: CI build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: ./build.sh ${{ matrix.os }}

    - name: Upload artifact
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: apnstool-macos-amd64
        path: bin/darwin_amd64/apnstool

    - name: Upload artifact
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: apnstool-macos-amd64
        path: bin/linux_amd64/apnstool

    - name: Upload artifact
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: binary-windows-amd64
        path: bin/windows_amd64/apnstool.exe
